In [1]:
import pandas as pd
import numpy as np
import decimal

In [2]:
data = pd.read_csv('soc-sign-bitcoinotc.csv', encoding='utf-8')
data = data.sort_values(by=['6', '2']) #ordenando o source e o target para contruir a matriz
data = data[data['4'] >= 8] #rating acima de 8
data.head()

6   2   4  1289241911.72836
253    1   2   8      1.296629e+09
11988  1   4  10      1.343107e+09
4995   1   6   8      1.308242e+09
410    1   7   9      1.298267e+09
51     1  17   9      1.290969e+09

In [4]:
s = list(data['6']) #source
t = list(data['2']) #target
nodes = list(set(s) | set(list(t))) #id's distintos

adjacence_dict = {
    node: [] for node in nodes
}

for i in range(len(s)):
    origin = s[i]
    destiny = t[i]
    adjacence_dict[origin].append(destiny)

In [5]:
def h_matrix(nodes):
    
    a = np.zeros(shape=(len(nodes), len(nodes)))
    
    for i in range(len(nodes)):
        for j in range(len(nodes)):
            source = nodes[i]
            target = nodes[j]
            if target in adjacence_dict[source]:
                '''if len(adjacence_dict[target]) > 0:
                    a[i][j] = float(1) / float(len(adjacence_dict[target]))
                else:
                    a[i][j] = float(0)'''
                a[j][i] = float(1) / float(len(adjacence_dict[source]))
                
    return np.matrix(a)

In [6]:
a = h_matrix(nodes) #matriz de transição
b = (float(1)/float(len(nodes)))*np.ones(shape=(len(nodes), len(nodes))) #matriz de 1's
m = (0.85*a) + (0.15*b)

print ('m:','\n',m)

m: 
 [[0.00016393 0.09460838 0.00016393 ... 0.00016393 0.00016393 0.00016393]
 [0.07743666 0.00016393 0.00016393 ... 0.00016393 0.00016393 0.00016393]
 [0.00016393 0.00016393 0.00016393 ... 0.00016393 0.00016393 0.00016393]
 ...
 [0.00016393 0.00016393 0.00016393 ... 0.00016393 0.00016393 0.00016393]
 [0.00016393 0.00016393 0.00016393 ... 0.00016393 0.00016393 0.00016393]
 [0.00016393 0.00016393 0.00016393 ... 0.00016393 0.00016393 0.00016393]]


In [7]:
#vetor com o page rank inicial dos investidores

v = (float(1)/len(nodes))*np.ones(shape=(len(nodes), 1))

print ('v:','\n',v)

v: 
 [[0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.0010929]
 [0.001

In [9]:
count = 0

def pageRank(v):
    global count
    if sum(abs(m*v-v)) > 0.001:
        count += 1
        #print ('count:',count)
        #print (m*v)
        #print ('sum(abs(m*v-v)):',sum(abs(m*v-v)))
        return pageRank(m*v)
    else:
        count += 1
        #print ('count:',count)
        #print (m*v)
        #print ('sum(abs(m*v-v)):',sum(abs(m*v-v)))
        return m*v

In [10]:
result = pageRank(v)
result = [cell.item(0,0) for cell in result]

In [11]:
r = {}
for i in range(len(result)):
    r[nodes[i]] = result[i]
    
r = sorted(r.items(), key=lambda x: x[1], reverse=True)

In [12]:
for i in r[0:5]:
    print('Id investidor:', i[0], ' Page Rank:', str(decimal.Decimal(i[1]))[:10])

Id investidor: 1  Page Rank: 0.00013899
Id investidor: 202  Page Rank: 0.00012469
Id investidor: 144  Page Rank: 0.00011742
Id investidor: 3996  Page Rank: 0.00009278
Id investidor: 361  Page Rank: 0.00009154
